FROM fedora:latest

RUN dnf install -y \
    gcc \
    gcc-c++ \
    cmake \
    ninja-build \
    git \
    qt6-qtbase-devel \
    qt6-qtdeclarative-devel \
    qt6-qtbase-gui \
    qt6-qtdeclarative \
    qt6-qtsvg-devel \
    qt6-qtimageformats \
    && dnf clean all

WORKDIR /workspace

COPY . .

CMD [ "/bin/bash" ]